### PR TITLE
linked css and js

### PR DESCRIPTION
**Pull request by nicnolen**

### CODE REVIEW

**Review by mmeans51 — APPROVED** [review]
sick code

**Review by ThanNguyen1 — COMMENTED** [review]
looks good

**Review by judy-martinez — APPROVED** [review]

**Review by CRZCode5150 — COMMENTED** [review]
Review check

**Review by felipezintzun — COMMENTED** [review]
Looks good!

**Review by ThanNguyen1 — APPROVED** [review]

**Pull request merged**
